<?php
namespace Tests\Feature;
use App\Models\Tenant;use App\Models\TenantMembership;use App\Models\TenantRegistrationRequest;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Str;use Laravel\Sanctum\Sanctum;use Tests\TestCase;
class ManagedPeopleCrudTest extends TestCase
{
 use RefreshDatabase;
 private function user(string $name='Admin',string $status='active'):User{return User::create(['public_id'=>(string)Str::ulid(),'identity_region'=>'ap-south-1','first_name'=>$name,'display_name'=>$name,'email_encrypted'=>'encrypted','email_hash'=>hash('sha256',Str::random()),'email_masked'=>'a***@example.com','phone_encrypted'=>'encrypted','phone_hash'=>hash('sha256',Str::random()),'phone_masked'=>'+91 ******1234','status'=>$status,'registered_via'=>'test','registration_started_at'=>now()]);}
 private function tenant(User $approver,string $name):Tenant{$applicant=$this->user($name.' Applicant');$registration=TenantRegistrationRequest::create(['public_id'=>(string)Str::ulid(),'applicant_user_id'=>$applicant->id,'registration_token_hash'=>hash('sha256',Str::random()),'institution_name'=>$name,'requested_slug'=>Str::slug($name).Str::lower(Str::random(4)),'constitution_type'=>'company','home_region'=>'ap-south-1','country_code'=>'IN','timezone'=>'Asia/Kolkata','default_language'=>'en','default_currency'=>'INR','status'=>'approved']);return Tenant::create(['public_id'=>(string)Str::ulid(),'name'=>$name,'slug'=>$registration->requested_slug,'constitution_type'=>'company','home_region'=>'ap-south-1','country_code'=>'IN','timezone'=>'Asia/Kolkata','default_language'=>'en','default_currency'=>'INR','source_registration_request_id'=>$registration->id,'approved_by'=>$approver->id,'approved_at'=>now()]);}
 public function test_super_admin_can_update_and_archive_user():void{$super=$this->user('Super');config(['ai_lms.super_admin_public_ids'=>[$super->public_id]]);$subject=$this->user('Old Name');Sanctum::actingAs($super);$this->patchJson('/api/v1/admin/users/'.$subject->public_id,['first_name'=>'New','last_name'=>'Name'])->assertOk()->assertJsonPath('data.display_name','New Name');$this->deleteJson('/api/v1/admin/users/'.$subject->public_id)->assertOk();$this->assertSoftDeleted('users',['id'=>$subject->id]);}
 public function test_tenant_admin_only_lists_teachers_in_selected_tenant():void{$admin=$this->user();$one=$this->tenant($admin,'One Academy');$two=$this->tenant($admin,'Two Academy');foreach([$one,$two]as$t)TenantMembership::create(['public_id'=>(string)Str::ulid(),'tenant_id'=>$t->id,'user_id'=>$admin->id,'role_code'=>'tenant_admin','status'=>'active','assigned_by'=>$admin->id,'approved_at'=>now()]);$teacher=$this->user('Teacher One');TenantMembership::create(['public_id'=>(string)Str::ulid(),'tenant_id'=>$one->id,'user_id'=>$teacher->id,'role_code'=>'teacher','status'=>'active','assigned_by'=>$admin->id,'approved_at'=>now()]);Sanctum::actingAs($admin);$this->getJson('/api/v1/tenant/teachers')->assertStatus(422);$this->withHeader('X-Tenant-ID',$one->public_id)->getJson('/api/v1/tenant/teachers')->assertOk()->assertJsonPath('data.0.display_name','Teacher One');$this->withHeader('X-Tenant-ID',$two->public_id)->getJson('/api/v1/tenant/teachers')->assertOk()->assertJsonCount(0,'data');}
}
