<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\User; use App\Models\UserApprovalAction; use App\Models\UserApprovalRequest; use App\Services\ContactIdentity; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class AdminUserController extends Controller
{
 public function index(Request $request): JsonResponse { $query=User::query()->latest(); if($request->filled('status')&&$request->string('status')!='all')$query->where('status',$request->string('status')); if($request->filled('search'))$query->where('display_name','like','%'.$request->string('search').'%'); return response()->json($query->paginate(25)); }
 public function store(Request $request, ContactIdentity $identity): JsonResponse { $data=$request->validate(['first_name'=>'required|string|max:100','last_name'=>'nullable|string|max:100','email'=>'required|email:rfc,dns|max:254','phone'=>['required','regex:/^\+[1-9][0-9]{7,14}$/'],'identity_region'=>'required|in:ap-south-1,eu-central-1,us-east-1']); $email=$identity->email($data['email']);$phone=$identity->phone($data['phone']); abort_if(User::where('email_hash',$email['hash'])->orWhere('phone_hash',$phone['hash'])->exists(),422,'A user already exists with the supplied email or mobile.'); $user=User::create([...$data,'public_id'=>(string)Str::ulid(),'display_name'=>trim($data['first_name'].' '.($data['last_name']??'')),'email_encrypted'=>$email['encrypted'],'email_hash'=>$email['hash'],'email_masked'=>$email['masked'],'phone_encrypted'=>$phone['encrypted'],'phone_hash'=>$phone['hash'],'phone_masked'=>$phone['masked'],'registered_via'=>'super_admin','registration_started_at'=>now(),'verification_expires_at'=>now()->addDay(),'created_by'=>$request->user()->id]); return response()->json(['data'=>$user],201); }
 public function update(Request $request,User $user,ContactIdentity $identity):JsonResponse{$data=$request->validate(['first_name'=>'sometimes|required|string|max:100','last_name'=>'nullable|string|max:100','email'=>'sometimes|required|email|max:254','phone'=>['sometimes','required','regex:/^\+[1-9][0-9]{7,14}$/'],'identity_region'=>'sometimes|required|in:ap-south-1,eu-central-1,us-east-1']);if(isset($data['email'])){$email=$identity->email($data['email']);abort_if(User::where('email_hash',$email['hash'])->where('id','!=',$user->id)->exists(),422,'Email already in use.');$data+=['email_encrypted'=>$email['encrypted'],'email_hash'=>$email['hash'],'email_masked'=>$email['masked'],'email_verified_at'=>null,'status'=>'pending_verification'];unset($data['email']);}if(isset($data['phone'])){$phone=$identity->phone($data['phone']);abort_if(User::where('phone_hash',$phone['hash'])->where('id','!=',$user->id)->exists(),422,'Mobile already in use.');$data+=['phone_encrypted'=>$phone['encrypted'],'phone_hash'=>$phone['hash'],'phone_masked'=>$phone['masked'],'phone_verified_at'=>null,'status'=>'pending_verification'];unset($data['phone']);}$first=$data['first_name']??$user->first_name;$last=array_key_exists('last_name',$data)?$data['last_name']:$user->last_name;$data['display_name']=trim($first.' '.($last??''));$data['updated_by']=$request->user()->id;$user->update($data);return response()->json(['data'=>$user->refresh()]);}
 public function destroy(Request $request,User $user):JsonResponse{abort_if($request->user()->is($user),422,'You cannot delete your own account.');abort_if($user->isSuperAdministrator(),422,'Bootstrap super administrators cannot be deleted here.');$user->tokens()->delete();$user->update(['status'=>'archived','updated_by'=>$request->user()->id]);$user->delete();return response()->json(['message'=>'User archived.']);}
 public function approve(Request $request, User $user): JsonResponse { abort_unless($user->status==='pending_approval',409,'User is not awaiting approval.'); DB::transaction(function()use($request,$user){$approval=$user->approvalRequests()->where('status','pending')->latest()->firstOrFail();abort_if($approval->requested_by===$request->user()->id,422,'The creator cannot approve their own request.');$approval->update(['status'=>'approved','decided_at'=>now(),'decided_by'=>$request->user()->id]);UserApprovalAction::create(['user_approval_request_id'=>$approval->id,'actor_user_id'=>$request->user()->id,'action'=>'approve','from_status'=>'pending','to_status'=>'approved','comments'=>$request->string('comment'),'created_at'=>now()]);$user->update(['status'=>'active','activated_at'=>now(),'activation_method'=>'approval']);}); return response()->json(['data'=>$user->refresh()]); }
 public function reject(Request $request, User $user): JsonResponse { $data=$request->validate(['reason'=>'required|string|max:500']); return $this->decide($request,$user,'rejected',$data['reason']); }
 public function suspend(Request $request, User $user): JsonResponse { $data=$request->validate(['reason'=>'required|string|max:500']);$user->tokens()->delete();$user->update(['status'=>'suspended','suspended_at'=>now(),'suspended_by'=>$request->user()->id,'suspension_reason'=>$data['reason'],'credentials_version'=>DB::raw('credentials_version + 1')]);return response()->json(['data'=>$user->refresh()]); }
 public function reactivate(Request $request, User $user): JsonResponse { abort_unless($user->status==='suspended',409);$user->update(['status'=>'active','suspended_at'=>null,'suspended_by'=>null,'suspension_reason'=>null]);return response()->json(['data'=>$user->refresh()]); }
 private function decide(Request $request, User $user,string $decision,string $reason): JsonResponse {DB::transaction(function()use($request,$user,$decision,$reason){$approval=$user->approvalRequests()->where('status','pending')->latest()->firstOrFail();$approval->update(['status'=>$decision,'decided_at'=>now(),'decided_by'=>$request->user()->id,'decision_reason'=>$reason]);UserApprovalAction::create(['user_approval_request_id'=>$approval->id,'actor_user_id'=>$request->user()->id,'action'=>$decision,'from_status'=>'pending','to_status'=>$decision,'comments'=>$reason,'created_at'=>now()]);$user->update(['status'=>'disabled']);});return response()->json(['data'=>$user->refresh()]);}
}
