<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\Tenant;use App\Models\TenantMembership;use App\Models\User;use App\Services\ContactIdentity;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class AdministratorController extends Controller
{
 public function index(Request $r):JsonResponse{$q=User::with(['tenantMemberships'=>fn($x)=>$x->with('tenant')->where('role_code','tenant_admin')])->where(fn($x)=>$x->where('registered_via','super_admin_administrator')->orWhereHas('tenantMemberships',fn($m)=>$m->where('role_code','tenant_admin')))->latest();if($r->filled('status')&&$r->string('status')!=='all')$q->where('status',$r->string('status'));if($r->filled('search'))$q->where('display_name','like','%'.$r->string('search').'%');$page=$q->paginate(20);$page->through(fn($u)=>$this->present($u));return response()->json($page);}
 public function store(Request $r,ContactIdentity $identity):JsonResponse{$d=$r->validate(['first_name'=>'required|string|max:100','last_name'=>'nullable|string|max:100','email'=>'required|email|max:254','phone'=>['required','regex:/^\+[1-9][0-9]{7,14}$/'],'tenant_public_ids'=>'sometimes|array','tenant_public_ids.*'=>'string|distinct']);$email=$identity->email($d['email']);$phone=$identity->phone($d['phone']);abort_if(User::where('email_hash',$email['hash'])->orWhere('phone_hash',$phone['hash'])->exists(),422,'Email or mobile already in use.');$user=DB::transaction(function()use($r,$d,$email,$phone){$u=User::create(['public_id'=>(string)Str::ulid(),'identity_region'=>'ap-south-1','first_name'=>$d['first_name'],'last_name'=>$d['last_name']??null,'display_name'=>trim($d['first_name'].' '.($d['last_name']??'')),'email_encrypted'=>$email['encrypted'],'email_hash'=>$email['hash'],'email_masked'=>$email['masked'],'phone_encrypted'=>$phone['encrypted'],'phone_hash'=>$phone['hash'],'phone_masked'=>$phone['masked'],'status'=>'pending_verification','registered_via'=>'super_admin_administrator','registration_started_at'=>now(),'verification_expires_at'=>now()->addDay(),'created_by'=>$r->user()->id]);$this->syncTenants($u,$d['tenant_public_ids']??[],$r->user()->id);return$u;});return response()->json(['data'=>$this->present($user->load('tenantMemberships.tenant'))],201);}
 public function update(Request $r,User $administrator,ContactIdentity $identity):JsonResponse{$this->assertAdministrator($administrator);$response=(new AdminUserController)->update($r,$administrator,$identity);if($r->has('tenant_public_ids'))$this->syncTenants($administrator,$r->validate(['tenant_public_ids'=>'array','tenant_public_ids.*'=>'string|distinct'])['tenant_public_ids'],$r->user()->id);return $response;}
 public function destroy(Request $r,User $administrator):JsonResponse{$this->assertAdministrator($administrator);return(new AdminUserController)->destroy($r,$administrator);}
 public function approve(Request $r,User $administrator):JsonResponse{$this->assertAdministrator($administrator);$response=(new AdminUserController)->approve($r,$administrator);$administrator->tenantMemberships()->where('role_code','tenant_admin')->update(['status'=>'active','approved_at'=>now()]);return$response;}
 public function reject(Request $r,User $administrator):JsonResponse{$this->assertAdministrator($administrator);$response=(new AdminUserController)->reject($r,$administrator);$administrator->tenantMemberships()->where('role_code','tenant_admin')->update(['status'=>'rejected']);return$response;}
 private function assertAdministrator(User $u):void{abort_unless($u->registered_via==='super_admin_administrator'||$u->tenantMemberships()->where('role_code','tenant_admin')->exists(),404);}
 private function syncTenants(User $u,array $ids,int $actor):void{foreach($ids as$id){$t=Tenant::where('public_id',$id)->where('status','active')->firstOrFail();TenantMembership::updateOrCreate(['tenant_id'=>$t->id,'user_id'=>$u->id],['public_id'=>(string)Str::ulid(),'role_code'=>'tenant_admin','status'=>$u->status==='active'?'active':'pending_approval','assigned_by'=>$actor,'approved_at'=>$u->status==='active'?now():null]);}}
 private function present(User $u):array{$membership=$u->tenantMemberships->first();return['public_id'=>$u->public_id,'display_name'=>$u->display_name,'first_name'=>$u->first_name,'last_name'=>$u->last_name,'email_masked'=>$u->email_masked,'phone_masked'=>$u->phone_masked,'status'=>$u->status,'role'=>'administrator','tenant'=>$membership?->tenant?->only(['public_id','name']),'created_at'=>$u->created_at];}
}
