<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\Tenant;use App\Models\TenantMembership;use App\Models\TenantRegistrationRequest;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class AdminTenantRegistrationController extends Controller
{
 public function index(Request $r):JsonResponse{$q=TenantRegistrationRequest::with(['applicant:id,public_id,display_name,email_masked,phone_masked,email_verified_at,phone_verified_at','documents','taxIdentifiers'])->latest();if($r->filled('status')&&$r->string('status')!=='all')$q->where('status',$r->string('status'));if($r->filled('search')){$s='%'.$r->string('search').'%';$q->where(fn($x)=>$x->where('institution_name','like',$s)->orWhere('legal_name','like',$s)->orWhereHas('applicant',fn($u)=>$u->where('display_name','like',$s)));}return response()->json($q->paginate(20));}
 public function update(Request $r,TenantRegistrationRequest $registration):JsonResponse{abort_if($registration->status==='approved',409,'Approved registrations must be updated through tenant management.');$d=$r->validate(['institution_name'=>'sometimes|required|string|max:200','legal_name'=>'nullable|string|max:250','requested_slug'=>'sometimes|required|alpha_dash|max:100|unique:tenant_registration_requests,requested_slug,'.$registration->id,'constitution_type'=>'sometimes|required|string|max:50']);$registration->update($d);return response()->json(['data'=>$registration->fresh(['applicant','documents','taxIdentifiers'])]);}
 public function destroy(TenantRegistrationRequest $registration):JsonResponse{abort_if($registration->status==='approved',409,'Approved registrations cannot be deleted.');$registration->delete();return response()->json(['message'=>'Tenant registration archived.']);}
 public function approve(Request $r,TenantRegistrationRequest $registration):JsonResponse{abort_unless($registration->status==='submitted',409);$tenant=DB::transaction(function()use($r,$registration){$t=Tenant::create(['public_id'=>(string)Str::ulid(),'name'=>$registration->institution_name,'legal_name'=>$registration->legal_name,'slug'=>$registration->requested_slug,'constitution_type'=>$registration->constitution_type,'home_region'=>$registration->home_region,'country_code'=>$registration->country_code,'timezone'=>$registration->timezone,'default_language'=>$registration->default_language,'default_currency'=>$registration->default_currency,'source_registration_request_id'=>$registration->id,'approved_by'=>$r->user()->id,'approved_at'=>now()]);TenantMembership::create(['public_id'=>(string)Str::ulid(),'tenant_id'=>$t->id,'user_id'=>$registration->applicant_user_id,'role_code'=>'tenant_admin','assigned_by'=>$r->user()->id,'approved_at'=>now()]);$registration->update(['status'=>'approved','decided_at'=>now(),'decided_by'=>$r->user()->id]);$registration->applicant->update(['status'=>'active','activated_at'=>now(),'activation_method'=>'tenant_registration_approval']);return$t;});return response()->json(['data'=>$tenant],201);}
 public function reject(Request $r,TenantRegistrationRequest $registration):JsonResponse{$d=$r->validate(['reason'=>'required|max:500']);abort_unless($registration->status==='submitted',409);$registration->update(['status'=>'rejected','decided_at'=>now(),'decided_by'=>$r->user()->id,'decision_reason'=>$d['reason']]);$registration->applicant->update(['status'=>'disabled']);return response()->json(['data'=>$registration->fresh()]);}
}
