<?php
namespace App\Http\Controllers\Api\V1;
use App\Contracts\OtpSender;use App\Http\Controllers\Controller;use App\Models\TenantMembership;use App\Models\User;use App\Services\ContactIdentity;use App\Services\TenantContext;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class TeacherController extends Controller
{
 public function __construct(private readonly TenantContext $context){}
 public function index(Request $r):JsonResponse{$tenant=$this->context->forAdministrator($r);$q=User::whereHas('tenantMemberships',fn($m)=>$m->where('tenant_id',$tenant->id)->where('role_code','teacher'))->latest();if($r->filled('status')&&$r->string('status')!=='all')$q->where('status',$r->string('status'));if($r->filled('search'))$q->where('display_name','like','%'.$r->string('search').'%');$page=$q->paginate(20);$page->through(fn($u)=>$this->present($u,$tenant));return response()->json($page);}
 public function store(Request $r,ContactIdentity $identity):JsonResponse{$tenant=$this->context->forAdministrator($r);$d=$r->validate(['first_name'=>'required|string|max:100','last_name'=>'nullable|string|max:100','email'=>'required|email|max:254','phone'=>['required','regex:/^\+[1-9][0-9]{7,14}$/']]);$email=$identity->email($d['email']);$phone=$identity->phone($d['phone']);abort_if(User::where('email_hash',$email['hash'])->orWhere('phone_hash',$phone['hash'])->exists(),422,'Email or mobile already in use.');$u=DB::transaction(function()use($r,$tenant,$d,$email,$phone){$u=User::create(['public_id'=>(string)Str::ulid(),'identity_region'=>$tenant->home_region,'first_name'=>$d['first_name'],'last_name'=>$d['last_name']??null,'display_name'=>trim($d['first_name'].' '.($d['last_name']??'')),'email_encrypted'=>$email['encrypted'],'email_hash'=>$email['hash'],'email_masked'=>$email['masked'],'phone_encrypted'=>$phone['encrypted'],'phone_hash'=>$phone['hash'],'phone_masked'=>$phone['masked'],'status'=>'pending_verification','registered_via'=>'tenant_admin_teacher','registration_started_at'=>now(),'verification_expires_at'=>now()->addDay(),'created_by'=>$r->user()->id]);TenantMembership::create(['public_id'=>(string)Str::ulid(),'tenant_id'=>$tenant->id,'user_id'=>$u->id,'role_code'=>'teacher','status'=>'pending_verification','assigned_by'=>$r->user()->id,'approved_at'=>now()]);return$u;});return response()->json(['data'=>$this->present($u,$tenant)],201);}
 public function update(Request $r,User $teacher,ContactIdentity $identity):JsonResponse{$tenant=$this->context->forAdministrator($r);$this->context->assertTeacher($tenant,$teacher);return(new AdminUserController)->update($r,$teacher,$identity);}
 public function destroy(Request $r,User $teacher):JsonResponse{$tenant=$this->context->forAdministrator($r);$this->context->assertTeacher($tenant,$teacher);$teacher->tenantMemberships()->where('tenant_id',$tenant->id)->where('role_code','teacher')->update(['status'=>'archived']);if(!$teacher->tenantMemberships()->where('status','active')->exists()){$teacher->tokens()->delete();$teacher->update(['status'=>'archived']);$teacher->delete();}return response()->json(['message'=>'Teacher archived for this tenant.']);}
 public function approve(Request $r,User $teacher):JsonResponse{$tenant=$this->context->forAdministrator($r);$this->context->assertTeacher($tenant,$teacher);abort_unless($teacher->email_verified_at&&$teacher->phone_verified_at&&$teacher->status==='pending_approval',409,'Teacher must verify email and mobile before approval.');DB::transaction(function()use($r,$tenant,$teacher){$teacher->update(['status'=>'active','activated_at'=>now(),'activation_method'=>'tenant_admin_approval']);$teacher->tenantMemberships()->where('tenant_id',$tenant->id)->where('role_code','teacher')->update(['status'=>'active','approved_at'=>now()]);});return response()->json(['data'=>$this->present($teacher->refresh(),$tenant)]);}
 public function reject(Request $r,User $teacher):JsonResponse{$tenant=$this->context->forAdministrator($r);$this->context->assertTeacher($tenant,$teacher);$r->validate(['reason'=>'required|string|max:500']);$teacher->tenantMemberships()->where('tenant_id',$tenant->id)->where('role_code','teacher')->update(['status'=>'rejected']);$teacher->update(['status'=>'disabled']);return response()->json(['data'=>$this->present($teacher->refresh(),$tenant)]);}
 public function sendVerification(Request $r,User $teacher,OtpSender $sender):JsonResponse{$tenant=$this->context->forAdministrator($r);$this->context->assertTeacher($tenant,$teacher);return(new VerificationController)->send($r,$teacher,$sender);}
 public function verify(Request $r,User $teacher):JsonResponse{$tenant=$this->context->forAdministrator($r);$this->context->assertTeacher($tenant,$teacher);$response=(new VerificationController)->verify($r,$teacher);if($teacher->fresh()->status==='pending_approval')$teacher->tenantMemberships()->where('tenant_id',$tenant->id)->where('role_code','teacher')->update(['status'=>'pending_approval']);return$response;}
 private function present(User $u,$tenant):array{return['public_id'=>$u->public_id,'display_name'=>$u->display_name,'first_name'=>$u->first_name,'last_name'=>$u->last_name,'email_masked'=>$u->email_masked,'phone_masked'=>$u->phone_masked,'status'=>$u->status,'role'=>'teacher','tenant'=>$tenant->only(['public_id','name']),'created_at'=>$u->created_at];}
}
