import './landing.css';

const features=[
  {icon:'live',title:'Live classrooms',text:'Host secure, interactive classes with self-hosted LiveKit, screen sharing, chat and recordings.'},
  {icon:'play',title:'Every content format',text:'Deliver hosted video, YouTube, PPT, documents, SCORM 1.2/2004 and Tin Can/xAPI courses.'},
  {icon:'offline',title:'Online and offline',text:'Keep learners moving across web and mobile, even where connectivity is limited or intermittent.'},
  {icon:'ai',title:'Teacher-verified AI',text:'Create courses and quizzes faster, analyse responses and recommend support—with teachers always in control.'},
  {icon:'check',title:'Active assessment',text:'Run quizzes, surveys, polls and session-wise feedback with immediate, useful learning signals.'},
  {icon:'chart',title:'Progress intelligence',text:'See completion, engagement and performance across learners, courses, teachers and institutions.'},
];

export function LandingPage(){return <div className="landing">
  <header className="landing-nav"><a className="landing-brand" href="/" aria-label="DK PreLearn home"><span>DK</span><strong>PreLearn</strong></a><nav aria-label="Public navigation"><a href="#platform">Platform</a><a href="#delivery">Learning</a><a href="#ai">AI</a><a href="#institutions">Institutions</a></nav><div className="landing-auth"><a className="text-link" href="/signin">Sign in</a><a className="nav-cta" href="/signup">Sign up</a></div></header>
  <main className="landing-main">
    <section className="landing-hero" id="platform"><div className="hero-copy"><div className="hero-label"><i></i>Modern learning, thoughtfully connected</div><h1>Teach brilliantly.<br/><em>Learn without limits.</em></h1><p>One intelligent learning platform for institutions to create, deliver and understand learning—live, online and offline.</p><div className="hero-actions"><a className="hero-primary" href="/signup">Start learning <span>→</span></a><a className="hero-secondary" href="/tenant-register"><Icon name="building"/> Register your institution</a></div><div className="trust-row"><div><strong>SCORM</strong><span>1.2 & 2004</span></div><div><strong>xAPI</strong><span>Tin Can ready</span></div><div><strong>LiveKit</strong><span>Self-hosted live</span></div><div><strong>3 regions</strong><span>India · EU · US</span></div></div></div>
      <div className="hero-visual" aria-label="Learning dashboard preview"><div className="visual-glow"></div><div className="preview-window"><div className="preview-top"><span className="mini-brand">DK</span><div className="preview-search"></div><div className="preview-avatar">AR</div></div><div className="preview-body"><aside><i></i><i></i><i></i><i></i></aside><div className="preview-content"><span className="preview-kicker">GOOD MORNING, ASHA</span><h2>Keep your momentum.</h2><div className="course-progress"><div className="course-image"><Icon name="book"/></div><div><small>LEADERSHIP ESSENTIALS</small><strong>Leading teams with clarity</strong><div className="progress"><i></i></div><span>72% complete</span></div></div><div className="preview-grid"><article><small>Next live class</small><strong>Today · 4:00 PM</strong><span><b></b> Strategy workshop</span></article><article><small>Learning streak</small><strong>12 days</strong><span>Personal best</span></article></div></div></div></div><div className="floating-card ai-card"><span><Icon name="spark"/></span><div><small>AI learning assistant</small><strong>3 concepts ready to review</strong></div></div><div className="floating-card live-card"><i></i><div><small>LIVE CLASS</small><strong>24 learners connected</strong></div></div></div>
    </section>
    <section className="feature-section" id="delivery"><div className="section-heading"><span className="section-kicker">Everything learning needs</span><h2>One platform. Every way to learn.</h2><p>Flexible enough for every institution, simple enough for every learner.</p></div><div className="feature-grid">{features.map(feature=><article key={feature.title} id={feature.icon==='ai'?'ai':undefined}><div className={`feature-icon icon-${feature.icon}`}><Icon name={feature.icon}/></div><h3>{feature.title}</h3><p>{feature.text}</p><a href="/signup" aria-label={`Explore ${feature.title}`}>Explore <span>→</span></a></article>)}</div></section>
    <section className="institution-section" id="institutions"><div><span className="section-kicker light">Built for learning organisations</span><h2>Your institution.<br/>Your identity.<br/><em>Your learning world.</em></h2><p>Launch a fully branded learning environment with independent administration, approvals and insight—backed by regional infrastructure built to scale.</p><ul><li><Icon name="check"/> Custom branding and institution workspace</li><li><Icon name="check"/> Super admin, administrator, teacher and student dashboards</li><li><Icon name="check"/> Verified registration and one-level-up approvals</li><li><Icon name="check"/> Secure regional deployment across India, Europe and US</li></ul><a href="/tenant-register">Register your institution <span>→</span></a></div><div className="region-orbit"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="region-core"><span>DK</span><strong>PreLearn</strong><small>Global learning cloud</small></div><div className="region region-india"><b>IN</b><span>India</span></div><div className="region region-eu"><b>EU</b><span>Europe</span></div><div className="region region-us"><b>US</b><span>United States</span></div></div></section>
    <section className="landing-cta"><span className="section-kicker">Ready when you are</span><h2>Make every learning moment count.</h2><p>Build a learning experience that feels modern, human and uniquely yours.</p><div><a className="hero-primary" href="/signup">Create your account <span>→</span></a><a className="hero-secondary" href="/signin">Sign in</a></div></section>
  </main>
  <footer className="landing-footer"><a className="landing-brand" href="/"><span>DK</span><strong>PreLearn</strong></a><p>Intelligent learning for everyone, everywhere.</p><div><a href="/signin">Sign in</a><a href="/signup">Sign up</a><a href="/tenant-register">Institution registration</a></div><small>© 2026 DK PreLearn. All rights reserved.</small></footer>
</div>}

function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={live:<><path d="M3 6.5A2.5 2.5 0 0 1 5.5 4h8A2.5 2.5 0 0 1 16 6.5v7a2.5 2.5 0 0 1-2.5 2.5h-8A2.5 2.5 0 0 1 3 13.5z"/><path d="m16 8 5-3v10l-5-3"/></>,play:<><rect x="3" y="4" width="18" height="16" rx="3"/><path d="m10 9 5 3-5 3z"/></>,offline:<><path d="M12 3v12m0 0 4-4m-4 4-4-4"/><path d="M5 17v3h14v-3"/></>,ai:<path d="M12 3 9.5 9.5 3 12l6.5 2.5L12 21l2.5-6.5L21 12l-6.5-2.5z"/>,check:<><path d="m5 12 4 4L19 6"/><circle cx="12" cy="12" r="9"/></>,chart:<><path d="M4 19V9m6 10V5m6 14v-7m5 7H2"/></>,building:<path d="M4 21V7l8-4 8 4v14M8 9h2m4 0h2M8 13h2m4 0h2M9 21v-4h6v4"/>,book:<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H11v16H6.5A2.5 2.5 0 0 0 4 21zM20 5.5A2.5 2.5 0 0 0 17.5 3H13v16h4.5A2.5 2.5 0 0 1 20 21z"/>,spark:<path d="m12 3 1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8z"/>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]??paths.spark}</svg>}
