import { FormEvent, useCallback, useEffect, useState } from 'react';
import { tenantApi, type TenantRegistration, type UpdateTenantRegistrationInput } from '../../../services/api';

export function TenantApprovals(){
  const[items,setItems]=useState<TenantRegistration[]>([]);const[status,setStatus]=useState('all');const[search,setSearch]=useState('');const[editing,setEditing]=useState<TenantRegistration|null>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError('');try{setItems((await tenantApi.list(status,search)).data)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load registrations')}finally{setLoading(false)}},[search,status]);
  useEffect(()=>{void load()},[load]);
  async function decide(item:TenantRegistration,action:'approve'|'reject'){try{if(action==='approve')await tenantApi.approve(item.public_id);else{const reason=prompt('Reason for rejection:');if(!reason)return;await tenantApi.reject(item.public_id,reason)}setNotice(`${item.institution_name} was ${action}d.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Action failed')}}
  async function update(input:UpdateTenantRegistrationInput){if(!editing)return;await tenantApi.update(editing.public_id,input);setEditing(null);setNotice('Tenant registration updated.');await load()}
  async function remove(item:TenantRegistration){if(!confirm(`Delete ${item.institution_name}? This action cannot be undone.`))return;try{await tenantApi.remove(item.public_id);setNotice(`${item.institution_name} was deleted.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Delete failed')}}
  return <div className="standalone-dashboard"><header className="topbar"><div><span className="eyebrow">Platform control</span><h1>Tenant registrations</h1></div><div className="actions"><a href="/tenant-register">+ Create tenant</a><a href="/">User approvals</a></div></header>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}{error&&<div className="error" role="alert">{error}</div>}<section className="panel"><div className="toolbar"><div className="tabs">{['all','submitted','approved','rejected'].map(value=><button className={status===value?'selected':''} onClick={()=>setStatus(value)} key={value}>{value}</button>)}</div><label className="search"><span>Search tenants</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Institution, legal name or applicant"/></label></div>{loading?<div className="empty">Loading registrations…</div>:items.length===0?<div className="empty">No tenant registrations found.</div>:items.map(item=><article className="tenant-row" key={item.public_id}><div><strong>{item.institution_name}</strong><span>{item.legal_name||item.constitution_type}</span></div><div><strong>{item.applicant.display_name}</strong><span>{item.applicant.email_masked} · {item.applicant.phone_masked}</span></div><div><span>{item.country_code} · {item.home_region}</span><small>{item.tax_identifiers.map(t=>`${t.identifier_type.toUpperCase()} ${t.masked_value}`).join(', ')}</small></div><div className="actions"><button onClick={()=>setEditing(item)}>Edit</button>{item.status==='submitted'&&<><button className="approve" onClick={()=>void decide(item,'approve')}>Approve & assign admin</button><button onClick={()=>void decide(item,'reject')}>Reject</button></>}<button className="danger" onClick={()=>void remove(item)}>Delete</button></div></article>)}</section>{editing&&<TenantDialog tenant={editing} onClose={()=>setEditing(null)} onSave={update}/>}</div>
}

function TenantDialog({tenant,onClose,onSave}:{tenant:TenantRegistration;onClose:()=>void;onSave:(input:UpdateTenantRegistrationInput)=>Promise<void>}){const[saving,setSaving]=useState(false);const[error,setError]=useState('');async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);const data=new FormData(event.currentTarget);try{await onSave({institution_name:String(data.get('institution_name')),legal_name:String(data.get('legal_name')||''),requested_slug:String(data.get('requested_slug')),constitution_type:String(data.get('constitution_type'))})}catch(reason){setError(reason instanceof Error?reason.message:'Update failed');setSaving(false)}}return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="tenant-edit-title"><div className="modal-head"><h2 id="tenant-edit-title">Edit tenant registration</h2><button aria-label="Close" onClick={onClose}>×</button></div>{error&&<div className="error">{error}</div>}<form onSubmit={submit}><label>Institution name<input name="institution_name" defaultValue={tenant.institution_name} required/></label><label>Legal name<input name="legal_name" defaultValue={tenant.legal_name}/></label><label>URL slug<input name="requested_slug" defaultValue={tenant.requested_slug} pattern="[a-z0-9-]+" required/></label><label>Constitution<select name="constitution_type" defaultValue={tenant.constitution_type}><option value="private_limited_company">Private company</option><option value="sole_proprietorship">Sole proprietorship</option><option value="partnership">Partnership</option><option value="association">Association</option><option value="trust">Trust</option><option value="educational_institution">Educational institution</option><option value="other">Other</option></select></label><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Update tenant'}</button></div></form></section></div>}
